In [1]:
import pandas as pd

In [8]:
df = pd.read_csv("op_bytes_per_batch.csv")
df['block_time'] = pd.to_datetime(df['block_time'])
df = df.set_index('block_time')
daily_counts = df.resample('D').size()

# 1. Convert daily_counts to a DataFrame
daily_counts_df = daily_counts.to_frame(name='count')

# 2. Calculate 30-day moving average and 30-day median
daily_counts_df['30d_moving_avg'] = daily_counts_df['count'].rolling(window=30).mean()
daily_counts_df['30d_moving_median'] = daily_counts_df['count'].rolling(window=30).median()

# 3. Calculate overall median, 25th percentile, 75th percentile, and average
overall_median = daily_counts_df['count'].median()
q25 = daily_counts_df['count'].quantile(0.25)
q75 = daily_counts_df['count'].quantile(0.75)
overall_average = daily_counts_df['count'].mean()

# Display the results
print(daily_counts_df.head())  # to see the first few rows with 30-day calculations
print(f"Overall Median: {overall_median}")
print(f"25th Percentile: {q25}")
print(f"75th Percentile: {q75}")
print(f"Overall Average: {overall_average}")

                           count  30d_moving_avg  30d_moving_median
block_time
2023-06-06 00:00:00+00:00     53             NaN                NaN
2023-06-07 00:00:00+00:00    665             NaN                NaN
2023-06-08 00:00:00+00:00    680             NaN                NaN
2023-06-09 00:00:00+00:00    725             NaN                NaN
2023-06-10 00:00:00+00:00    761             NaN                NaN
Overall Median: 711.5
25th Percentile: 546.0
75th Percentile: 900.25
Overall Average: 766.0192307692307

In [13]:
daily_counts_df[100:]

                           count  30d_moving_avg  30d_moving_median
block_time
2023-09-14 00:00:00+00:00    594      717.033333              652.0
2023-09-15 00:00:00+00:00    664      694.633333              652.0
2023-09-16 00:00:00+00:00    499      677.200000              631.5
2023-09-17 00:00:00+00:00    467      666.300000              615.0
2023-09-18 00:00:00+00:00    546      661.500000              604.0
2023-09-19 00:00:00+00:00    561      658.633333              590.5
2023-09-20 00:00:00+00:00    546      653.666667              585.0
2023-09-21 00:00:00+00:00    569      649.433333              578.0
2023-09-22 00:00:00+00:00    593      644.666667              578.0
2023-09-23 00:00:00+00:00    541      640.800000              571.0
2023-09-24 00:00:00+00:00    458      636.966667              568.5
2023-09-25 00:00:00+00:00   1002      652.200000              576.0
2023-09-26 00:00:00+00:00    900      664.200000              585.0
2023-09-27 00:00:00+00:00    656      645.300000              585.0
2023-09-28 00:00:00+00:00    669      636.633333              585.0
2023-09-29 00:00:00+00:00    539      630.400000              576.0
2023-09-30 00:00:00+00:00    614      625.266667              576.0
2023-10-01 00:00:00+00:00    455      618.366667              568.5
2023-10-02 00:00:00+00:00    495      616.366667              568.5
2023-10-03 00:00:00+00:00    500      616.633333              568.5
2023-10-04 00:00:00+00:00    461      613.933333              568.5
2023-10-05 00:00:00+00:00    463      609.800000              564.5
2023-10-06 00:00:00+00:00    451      604.300000              553.5
2023-10-07 00:00:00+00:00    396      597.033333              546.0
2023-10-08 00:00:00+00:00    393      590.700000              543.5
2023-10-09 00:00:00+00:00    788      599.633333              546.0
2023-10-10 00:00:00+00:00    643      603.666667              553.5
2023-10-11 00:00:00+00:00    611      585.966667              553.5
2023-10-12 00:00:00+00:00    631      575.766667              553.5
2023-10-13 00:00:00+00:00    490      573.166667              546.0
2023-10-14 00:00:00+00:00    400      566.700000              543.5
2023-10-15 00:00:00+00:00    408      558.166667              540.0
2023-10-16 00:00:00+00:00    458      556.800000              540.0
2023-10-17 00:00:00+00:00    498      557.833333              540.0
2023-10-18 00:00:00+00:00    457      554.866667              519.5
2023-10-19 00:00:00+00:00    450      551.166667              499.0
2023-10-20 00:00:00+00:00    480      548.966667              496.5
2023-10-21 00:00:00+00:00    442      544.733333              492.5
2023-10-22 00:00:00+00:00    434      539.433333              485.0
2023-10-23 00:00:00+00:00   1201      561.433333              485.0
2023-10-24 00:00:00+00:00    818      573.433333              492.5
2023-10-25 00:00:00+00:00    688      562.966667              492.5
2023-10-26 00:00:00+00:00    643      554.400000              492.5
2023-10-27 00:00:00+00:00    526      550.066667              492.5
2023-10-28 00:00:00+00:00    448      542.700000              485.0
2023-10-29 00:00:00+00:00    426      538.933333              471.5
2023-10-30 00:00:00+00:00    456      533.666667              462.0
2023-10-31 00:00:00+00:00    582      537.900000              471.5
2023-11-01 00:00:00+00:00    519      538.700000              471.5
2023-11-02 00:00:00+00:00    580      541.366667              471.5
2023-11-03 00:00:00+00:00    515      543.166667              485.0
2023-11-04 00:00:00+00:00    527      545.300000              494.0
2023-11-05 00:00:00+00:00    613      550.700000              506.5
2023-11-06 00:00:00+00:00   1480      586.833333              517.0
2023-11-07 00:00:00+00:00    946      605.266667              522.5
2023-11-08 00:00:00+00:00    390      592.000000              517.0